---

- include: ntp.yml
- include: limits.yml
- include: javaversion.yml
- include: phantomjs.yml

- name: Set up looker/.lookerjmx directory
  file: state=directory path={{ jmx_security_dir }} mode=0700 owner={{ lookerops }} group={{ lookeropsgr }}

- name: Set up looker/looker directory
  file: state=directory path={{ deploy_dir }} mode=0750 owner={{ lookerops }} group={{ lookeropsgr }}

- name: Copy jar file to looker home
  get_url: url={{ s3_url }}/{{ deploy_jar }} dest={{ deploy_dir }}/looker.jar mode=0640 owner={{ lookerops }} group={{ lookeropsgr }}

- name: Copy jmx security files to looker home
  copy: src={{ item }} dest={{ jmx_security_dir }}/{{ item }} owner={{ lookerops }} group={{ lookeropsgr }} mode=0400
  with_items:
    - jmxremote.access
    - jmxremote.password

- name: Copy looker startup files
  template: src=looker_init.j2 dest=/etc/init.d/looker mode=0755 owner=root group=root

- template: src=looker.j2 dest={{ deploy_dir }}/looker mode=0750 owner={{ lookerops }} group={{ lookeropsgr }}

- name: Start Looker
  service: name=looker state=started enabled=yes

- include: cron.yml

- meta: flush_handlers
